const te=new TextEncoder();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}});
const text=(value,status=200,headers={})=>new Response(value,{status,headers:{'content-type':'text/html;charset=UTF-8',...headers}});
const b64u=s=>btoa(String.fromCharCode(...new Uint8Array(s))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const unb64=s=>Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
async function sign(value,secret){return b64u(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',te.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),te.encode(value)))}
async function session(request,env){const raw=(request.headers.get('cookie')||'').match(/(?:^|; )winnway_session=([^;]+)/)?.[1];if(!raw)return false;const [payload,signature]=raw.split('.');if(!payload||!signature||!env.SESSION_SECRET)return false;const expected=await sign(payload,env.SESSION_SECRET);if(expected!==signature)return false;try{return JSON.parse(new TextDecoder().decode(unb64(payload))).exp>Date.now()}catch{return false}}
async function createSession(env){const payload=b64u(te.encode(JSON.stringify({exp:Date.now()+1000*60*60*24*30})));return payload+'.'+await sign(payload,env.SESSION_SECRET)}
function loginPage(error=''){return '<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Winnway Studio</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f2e9dc;color:#251619;font:16px system-ui,"Microsoft JhengHei",sans-serif}.box{width:min(400px,88vw);background:#fffdfa;padding:38px;box-shadow:0 20px 60px #4b2b2730}.brand{font:700 25px Georgia,serif;letter-spacing:.1em}.brand small{display:block;color:#766963;font:11px Georgia,serif;letter-spacing:.18em;margin-top:6px}label{display:block;margin:30px 0 8px}input,button{box-sizing:border-box;width:100%;padding:13px;font:inherit}input{border:1px solid #d8caba}button{margin-top:14px;border:0;background:#7c2d38;color:#fff}.error{color:#8b2f3a;font-size:13px}</style><main class="box"><div class="brand">WINNWAY STUDIO<small>THE ART OF DISCOVERY</small></div><label>網站共用密碼</label><form method="post" action="/api/login"><input name="password" type="password" required autofocus><button>進入網站</button></form>'+error+'</main></html>'}
async function data(request){try{return await request.json()}catch{return {}}}
async function cellar(env){const items=(await env.CELLAR_DB.prepare('SELECT * FROM cellar_items ORDER BY updated_at DESC').all()).results;const entries=(await env.CELLAR_DB.prepare('SELECT * FROM cellar_entries ORDER BY id DESC').all()).results;return {items,entries}}
async function api(request,env,url){const path=url.pathname;if(path==='/api/cellar'&&request.method==='GET')return json(await cellar(env));const body=await data(request);
 if(path==='/api/cellar/add'&&request.method==='POST'){if(!body.wineId)return json({error:'缺少酒款'},400);await env.CELLAR_DB.prepare("INSERT OR IGNORE INTO cellar_items(wine_id) VALUES(?1)").bind(body.wineId).run();return json(await cellar(env))}
 if(path==='/api/cellar/remove'&&request.method==='POST'){await env.CELLAR_DB.batch([env.CELLAR_DB.prepare('DELETE FROM cellar_entries WHERE wine_id=?1').bind(body.wineId),env.CELLAR_DB.prepare('DELETE FROM cellar_items WHERE wine_id=?1').bind(body.wineId)]);return json(await cellar(env))}
 if(path==='/api/cellar/meta'&&request.method==='POST'){await env.CELLAR_DB.prepare("UPDATE cellar_items SET location=?2,note=?3,updated_at=CURRENT_TIMESTAMP WHERE wine_id=?1").bind(body.wineId,String(body.location||''),String(body.note||'')).run();return json(await cellar(env))}
 if(path==='/api/cellar/entry'&&request.method==='POST'){const qty=Math.max(1,Number(body.quantity)||1),type=body.type==='out'?'out':'in';const rows=(await env.CELLAR_DB.prepare("SELECT COALESCE(SUM(CASE WHEN entry_type='out' THEN -quantity ELSE quantity END),0) stock FROM cellar_entries WHERE wine_id=?1").bind(body.wineId).all()).results;if(type==='out'&&qty>Number(rows[0]?.stock||0))return json({error:'取出數量不能大於現有庫存'},400);await env.CELLAR_DB.prepare('INSERT INTO cellar_entries(wine_id,entry_date,entry_type,quantity,reason,person_name) VALUES(?1,?2,?3,?4,?5,?6)').bind(body.wineId,body.date||new Date().toISOString().slice(0,10),type,qty,String(body.reason||''),String(body.personName||'未填寫')).run();return json(await cellar(env))}
 return json({error:'找不到功能'},404)}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/login')return text(loginPage());if(url.pathname==='/api/login'&&request.method==='POST'){const f=await request.formData();if(!env.SITE_PASSWORD||!env.SESSION_SECRET)return text(loginPage('<p class="error">網站尚未完成安全設定。</p>'),503);if(String(f.get('password')||'')!==env.SITE_PASSWORD)return text(loginPage('<p class="error">密碼不正確，請再試一次。</p>'),401);const cookie=await createSession(env);return new Response(null,{status:302,headers:{location:'/', 'set-cookie':'winnway_session='+cookie+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000'}})}if(url.pathname==='/api/logout')return new Response(null,{status:302,headers:{location:'/login','set-cookie':'winnway_session=; Path=/; HttpOnly; Secure; Max-Age=0'}});if(!await session(request,env))return Response.redirect(url.origin+'/login',302);if(url.pathname.startsWith('/api/'))return api(request,env,url);return env.ASSETS.fetch(request)}};